### ISSUE TITLE
not able to install the plugin

### ISSUE THREAD

**Issue by RNF-SI** [tpartner/LimeSurvey-Searchable-Dropdown#2]
I'm not able to install the plugin in LimeSurvey 5.6.18. 
It seems to read the XML file because it shows me the description, version... but after clicking on the installation button it tells me it's impossible to analyze the config.xml file.

**Comment by tpartner** [comment]
My guess is that you have a wrong file structure. You cannot install thebzip file directly downloaded from GitHub.

Make sure you follow the instructions exactly. 

"Theme manager (4.x - 5.x) - Extract the download, **compress (zip) the Searchable-Dropdown folder** and import via the theme manager."

**Comment by RNF-SI** [comment]
Thank's for your answer. I'm sorry I didn't understand that all the tools offered in the limestore were not installed via the plugin manager. It's work!
